[__config__]
oldver = "oldver.json"

[opencode-git]
source = "git"
git = "https://github.com/anomalyco/opencode.git"
prefix = "v"

[dnstwist]
source = "pypi"
pypi = "dnstwist"

[amass-bin]
source = "git"
git = "https://github.com/owasp-amass/amass.git"
prefix = "v"

[amass-git]
source = "git"
git = "https://github.com/owasp-amass/amass.git"
prefix = "v"

[apm-bin]
source = "git"
git = "https://github.com/microsoft/apm.git"
prefix = "v"

[apm]
source = "github"
github = "microsoft/apm"
use_latest_tag = true
prefix = "v"

[python-whois]
source = "pypi"
pypi = "python-whois"

[ranger-doas]
source = "github"
github = "ranger/ranger"
use_latest_tag = true
prefix = "v"

[jules-tools]
source = "npm"
npm = "@google/jules"

[opendoas]
source = "github"
github = "Duncaen/OpenDoas"
use_latest_tag = true

[go-regal-bin]
source = "github"
github = "StyraInc/regal"
use_latest_tag = true
prefix = "v"

[clash-geoip]
source = "git"
git = "https://github.com/Loyalsoldier/geoip.git"
[pkl-lsp-bin]
source = "github"
github = "apple/pkl-lsp"
use_latest_tag = true

[pkl-lsp]
source = "git"
git = "https://github.com/apple/pkl-lsp.git"

[doas-bash-completion]
source = "github"
github = "aarchetype/bash-completion"
use_latest_tag = true

[seiche]
source = "github"
github = "SeicheAcoustics/Seiche"
use_latest_release = true
prefix = "v"

[python-pytest-recording]
source = "git"
git = "https://github.com/kiwicom/pytest-recording.git"
prefix = "v"

[python-sqlite-fts4]
source = "git"
git = "https://github.com/simonw/sqlite-fts4.git"
use_latest_tag = true

[apm-go-git]
source = "git"
git = "https://github.com/githubnext/apm.git"

[python-frontmatter]
source = "pypi"
pypi = "python-frontmatter"

[python-llm]
source = "git"
git = "https://github.com/simonw/llm.git"

[python-llm-github-models]
source = "pypi"
pypi = "llm-github-models"

[python-click-default-group]
source = "git"
git = "https://github.com/click-contrib/click-default-group.git"
prefix = "v"

[python-condense-json]
source = "pypi"
pypi = "condense-json"

[sqlite-utils]
source = "pypi"
pypi = "sqlite-utils"

[python-sqlite-migrate]
source = "git"
git = "https://github.com/simonw/sqlite-migrate.git"

[python-azure-ai-inference]
source = "pypi"
pypi = "azure-ai-inference"

[python-azure-core]
source = "git"
git = "https://github.com/Azure/azure-sdk-for-python.git"
prefix = "v"

[bifrost]
source = "git"
git = "https://github.com/maximhq/bifrost.git"
prefix = "transports/v"
