[__config__]

[opencode-git]
source = "git"
git = "https://github.com/anomalyco/opencode.git"
prefix = "v"

[context7-cli]
source = "npm"
npm = "ctx7"

[amass-bin]
source = "git"
git = "https://github.com/owasp-amass/amass.git"
prefix = "v"

[amass-git]
source = "git"
git = "https://github.com/owasp-amass/amass.git"
prefix = "v"

[python-whois]
source = "pypi"
pypi = "python-whois"