[__config__]
oldver = "oldver.json"
newver = "newver.json"

[opencode-git]
source = "git"
git = "https://github.com/anomalyco/opencode.git"
prefix = "v"

[dnstwist]
source = "pypi"
pypi = "dnstwist"

[amass-bin]
source = "git"
git = "https://github.com/owasp-amass/amass.git"
prefix = "v"

[amass-git]
source = "git"
git = "https://github.com/owasp-amass/amass.git"
prefix = "v"

[apm-bin]
source = "git"
git = "https://github.com/microsoft/apm.git"
prefix = "v"

[python-whois]
source = "pypi"
pypi = "python-whois"

[ranger-doas]
source = "github"
github = "ranger/ranger"
use_latest_tag = true
prefix = "v"

[jules-tools]
source = "npm"
npm = "@google/jules"

[opendoas]
source = "github"
github = "Duncaen/OpenDoas"
use_latest_tag = true

[go-regal-bin]
source = "github"
github = "StyraInc/regal"
use_latest_tag = true
prefix = "v"

[clash-geoip]
source = "git"
git = "https://github.com/Loyalsoldier/geoip.git"
[pkl-lsp-bin]
source = "github"
github = "colelawrence/pkl-lsp"
use_latest_tag = true
