[opendoas]
source = "github"
github = "Duncaen/OpenDoas"
use_latest_tag = true
prefix = "v"
[opendoas-arch]
source = "git"
git = "https://gitlab.archlinux.org/archlinux/packaging/packages/opendoas.git"
branch = "main"
use_commit = true
